#!/usr/bin/env node
// Assembles the publishable routing package in pkg/: Sabi as a thin library — the decision core
// that chooses model, reasoning effort and provider for a round. This is the product; the CLI and
// the per-host adapters are consumers of it.
//
// Build: SABI_ROUTER_VERSION=<version> node pack.mjs    (the release workflow passes the tag).
//
// The workspace keeps the internal name `@sabi/core` so no import across the monorepo changes.
// The published name is `@vizuh/sabi-router`, the same source-to-staging pattern the controller and
// the Command Code mod already use.
import { copyFileSync, cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { build } from 'esbuild'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../..')
const outDir = path.join(here, 'pkg')
const distDir = path.join(outDir, 'dist')

const source = JSON.parse(readFileSync(path.join(here, 'package.json'), 'utf8'))
const version = (process.env.SABI_ROUTER_VERSION?.trim() || source.version).replace(/^router-v/, '').replace(/^v/, '')

rmSync(outDir, { recursive: true, force: true })
mkdirSync(distDir, { recursive: true })

await build({
  entryPoints: [path.join(here, 'src/index.ts')],
  outfile: path.join(distDir, 'index.mjs'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  // Readable on purpose: the shipped file is the reviewer's only copy of what runs.
  minify: false,
  legalComments: 'none',
  banner: {
    js: `// @vizuh/sabi ${version} — generated by pack.mjs from packages/core/src/index.ts.\n// Source and docs: https://github.com/vizuh/sabi`,
  },
})

// Every host integration ships in this package, not only Command Code. The short name used to mean
// "the Command Code mod"; it now means Sabi, and each host's entry point is a file in here. The
// per-host packages remain as optional slices for people who want one integration and nothing else.
mkdirSync(path.join(outDir, 'mods/command-code'), { recursive: true })
mkdirSync(path.join(outDir, 'mods/oh-my-pi'), { recursive: true })
mkdirSync(path.join(outDir, 'plugins/opencode'), { recursive: true })
mkdirSync(path.join(outDir, 'plugins/orca'), { recursive: true })

await build({
  entryPoints: [path.join(repoRoot, 'packages/adapters/command-code/mod/sabi.ts')],
  outfile: path.join(outDir, 'mods/command-code/sabi.mjs'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  minify: false,
  legalComments: 'none',
  banner: {
    js: `// @vizuh/sabi ${version} — Command Code mod, generated by pack.mjs from packages/adapters/command-code/mod/sabi.ts.\n// Source and docs: https://github.com/vizuh/sabi`,
  },
})

// The remaining hosts load a file that is already self-contained, so these are copies, not builds.
copyFileSync(path.join(repoRoot, 'packages/adapters/oh-my-pi/src/sabi-extension.mjs'), path.join(outDir, 'mods/oh-my-pi/sabi-extension.mjs'))
copyFileSync(path.join(repoRoot, 'packages/adapters/opencode/src/sabi-hook.mjs'), path.join(outDir, 'plugins/opencode/sabi-hook.mjs'))
copyFileSync(path.join(repoRoot, 'packages/adapters/orca/main.mjs'), path.join(outDir, 'plugins/orca/main.mjs'))
copyFileSync(path.join(repoRoot, 'packages/adapters/orca/orca-plugin.json'), path.join(outDir, 'plugins/orca/orca-plugin.json'))
copyFileSync(path.join(repoRoot, 'sabi.config.json'), path.join(outDir, 'sabi.config.json'))

const bundled = readFileSync(path.join(distDir, 'index.mjs'), 'utf8')
// The library is self-contained by design: a routing package that cannot be imported outside the
// repository is a broken product, and the failure would only surface for a consumer.
for (const forbidden of ['@sabi/core', '@commandcode/harness']) {
  if (bundled.includes(`from '${forbidden}'`) || bundled.includes(`from "${forbidden}"`)) {
    throw new Error(`bundle still imports ${forbidden} — it would fail outside the repository`)
  }
}

copyFileSync(path.join(repoRoot, 'LICENSE'), path.join(outDir, 'LICENSE'))
copyFileSync(path.join(here, 'README.md'), path.join(outDir, 'README.md'))
// The typed entry points at `src/`, so the source tree ships with the bundle. Tests are not part of
// it: a consumer needs the routing code, not the suite that checks it.
cpSync(path.join(here, 'src'), path.join(outDir, 'src'), { recursive: true })

writeFileSync(
  path.join(outDir, 'package.json'),
  `${JSON.stringify(
    {
      name: '@vizuh/sabi',
      version,
      description:
        'Sabi: the thin routing layer for coding agents — chooses model, reasoning effort and provider per round from trajectory evidence. Decides model, reasoning effort and provider for each round from trajectory evidence — tool results, failures, context pressure, verification — instead of pinning one model to a whole task. The engine behind the Sabi CLI, the local proxy and the per-host adapters. Carries every host integration: Command Code, Oh My Pi, OpenCode and Orca.',
      type: 'module',
      license: source.license,
      repository: { type: 'git', url: 'git+https://github.com/vizuh/sabi.git', directory: 'packages/core' },
      homepage: 'https://github.com/vizuh/sabi',
      bugs: { url: 'https://github.com/vizuh/sabi/issues' },
      keywords: [
        'sabi',
        'llm-routing',
        'model-routing',
        'ai-agents',
        'coding-agents',
        'inference-scheduling',
        'reasoning-effort',
        'trajectory',
        'openai-compatible',
        'typescript',
      ],
      main: './dist/index.mjs',
      module: './dist/index.mjs',
      // The core is TypeScript-first and its relative imports carry explicit `.ts` extensions, so
      // per-file declaration emit would ship specifiers consumers cannot resolve. The package
      // bundles the runnable ESM entry and ships `src/` as the typed entry — the shape
      // TypeScript sources support natively, with no fragile second build step.
      types: './src/index.ts',
      exports: {
        '.': { types: './src/index.ts', import: './dist/index.mjs', default: './dist/index.mjs' },
      },
      files: [
        'dist/index.mjs', 'src', 'sabi.config.json', 'README.md', 'LICENSE',
        'mods/command-code/sabi.mjs', 'mods/oh-my-pi/sabi-extension.mjs',
        'plugins/opencode/sabi-hook.mjs', 'plugins/orca/main.mjs', 'plugins/orca/orca-plugin.json',
      ],
      commandcode: { mods: ['./mods/command-code/sabi.mjs'] },
      omi: { extension: './mods/oh-my-pi/sabi-extension.mjs' },
      opencode: { plugin: './plugins/opencode/sabi-hook.mjs' },
      orca: { plugin: './plugins/orca/orca-plugin.json', main: './plugins/orca/main.mjs' },
      publishConfig: { access: 'public' },
    },
    null,
    2,
  )}\n`,
)

console.log(`packed @vizuh/sabi ${version} → ${path.relative(repoRoot, outDir)}`)
