#!/usr/bin/env node
// Assembles the publishable package in pkg/: one bundled mod file plus the repository's default
// sabi.config.json and a manifest with no dev-only fields. The repository source stays untouched,
// so a clone (and a local-path mod install) keeps loading mod/sabi.ts directly, while an npm
// install gets a single self-contained file with no runtime dependencies.
//
// Build: SABI_VERSION=<version> node pack.mjs    (the release workflow passes the tag).
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { build } from 'esbuild'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../../..')
const outDir = path.join(here, 'pkg')
const outMod = path.join(outDir, 'mod/sabi.mjs')

const source = JSON.parse(readFileSync(path.join(here, 'package.json'), 'utf8'))
const version = (process.env.SABI_VERSION?.trim() || source.version).replace(/^v/, '')

rmSync(outDir, { recursive: true, force: true })
mkdirSync(path.dirname(outMod), { recursive: true })

await build({
  entryPoints: [path.join(here, 'mod/sabi.ts')],
  outfile: outMod,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  // Readable on purpose: the shipped file is the reviewer's only copy of what runs.
  minify: false,
  legalComments: 'none',
  banner: {
    js: `// @vizuh/sabi-commandcode ${version} — generated by pack.mjs from packages/adapters/command-code/mod/sabi.ts.\n// Source and docs: https://github.com/vizuh/sabi`,
  },
})

const bundled = readFileSync(outMod, 'utf8')
for (const forbidden of ['@sabi/core', '@commandcode/harness']) {
  if (bundled.includes(`from '${forbidden}'`) || bundled.includes(`from "${forbidden}"`)) {
    throw new Error(`bundle still imports ${forbidden} — it would fail outside the repository`)
  }
}

copyFileSync(path.join(repoRoot, 'sabi.config.json'), path.join(outDir, 'sabi.config.json'))
copyFileSync(path.join(repoRoot, 'LICENSE'), path.join(outDir, 'LICENSE'))
copyFileSync(path.join(here, 'README.md'), path.join(outDir, 'README.md'))
writeFileSync(
  path.join(outDir, 'package.json'),
  `${JSON.stringify(
    {
      name: '@vizuh/sabi-commandcode',
      version,
      description: source.description,
      type: 'module',
      license: source.license,
      repository: source.repository,
      homepage: source.homepage,
      keywords: source.keywords,
      publishConfig: { access: 'public' },
      commandcode: { mods: ['./mod/sabi.mjs'] },
      files: ['mod/sabi.mjs', 'sabi.config.json', 'README.md', 'LICENSE'],
    },
    null,
    2,
  )}\n`,
)

console.log(`packed @vizuh/sabi-commandcode ${version} → ${path.relative(repoRoot, outDir)}`)
